### ISSUE TITLE
Kindle Voyage 电源键无法停止服务

### ISSUE THREAD

**Issue by Young-Lord** [guo-yong-zhi/KOSSH#1]
具体来说，`lipc-wait-event  com.lab126.hal powerButtonPressed | read event`不会在电源按钮按下是响应或是停止阻塞，因此电源键无法停止服务。
Kindle：Kindle Voyage，固件版本 5.13.6

**Comment by guo-yong-zhi** [comment]
和这个应该是一样的问题：https://github.com/guo-yong-zhi/kindle-filebrowser/issues/1

你可以试下手动关闭WiFi（即进入飞行模式）能否停止服务吗？

**Comment by Young-Lord** [comment]
> 和这个应该是一样的问题：[guo-yong-zhi/kindle-filebrowser#1](https://github.com/guo-yong-zhi/kindle-filebrowser/issues/1)
> 
> 你可以试下手动关闭WiFi（即进入飞行模式）能否停止服务吗？具体而言期待这句话生效：https://github.com/guo-yong-zhi/KOSSH/blob/main/KOSSH.sh#LL22C37-L22C55

可以停止。仿照这个思路我在菜单里加了个`STOP-KOSSH.sh`发送这个event

**Comment by guo-yong-zhi** [comment]
阻止锁屏也需要关闭，可以参考这个：https://github.com/guo-yong-zhi/kindle-filebrowser/blob/main/kill.sh

**Comment by guo-yong-zhi** [comment]
方便的话可以提个PR？

**Comment by Young-Lord** [comment]
> 阻止锁屏也需要关闭，可以参考这个：https://github.com/guo-yong-zhi/kindle-filebrowser/blob/main/kill.sh

我看`KOSSH.sh`里已经实现了恢复锁屏的逻辑，只要给它发那个event就好了吧，不用再写一个恢复锁屏

**Comment by guo-yong-zhi** [comment]
起到兜底作用，防止有的机型连发送event命令也无效

**Comment by guo-yong-zhi** [comment]
https://github.com/guo-yong-zhi/KOSSH/pull/2
